name: Java CI with Gradle

on:
  pull_request:
    branches: [ "main", "dev" ]
    types: [ opened, synchronize, reopened ]
    paths:
      - server/**

jobs:
  server-ci:
    defaults:
      run:
        working-directory: server

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew

      - name: Test with Gradle
        run: ./gradlew test

      - name: Build Gradle
        run: ./gradlew build